import { Router } from 'express';
import { createMedicine, getMedicine, listMedicines, searchMedicines } from '../controllers/medicineController.js';
import { permit, protect } from '../middleware/auth.js';
import { requireFields } from '../middleware/validate.js';
const router = Router();
router.get('/', listMedicines);
router.get('/search', searchMedicines);
router.post('/', protect, permit('admin'), requireFields('name', 'genericName', 'category'), createMedicine);
router.get('/:id', getMedicine);
export default router;
